version: '3'
services:
  local-db:
    image: library/mysql:5.7
    platform: linux/amd64
    container_name: local-db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: masterpw
      MYSQL_DATABASE: subway
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql --user 1000
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
  local-redis:
    image: redis:7.0.2
    container_name: local-redis
    restart: always
    ports:
      - 16379:6379
#  master-db:
#    image: library/mysql:5.7
#    platform: linux/amd64
#    container_name: master-db
#    restart: always
#    ports:
#      - 13306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: masterpw
#      MYSQL_DATABASE: subway
#      TZ: Asia/Seoul
#    volumes:
#      - ./db/mysql/master/data:/var/lib/mysql --user 1000
#      - ./db/mysql/master/config:/etc/mysql/conf.d
#      - ./db/mysql/master/init:/docker-entrypoint-initdb.d
#  slave-db:
#    image: library/mysql:5.7
#    platform: linux/amd64
#    container_name: slave-db
#    restart: always
#    ports:
#      - 13307:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: slavepw
#      MYSQL_DATABASE: subway
#      TZ: Asia/Seoul
#    volumes:
#      - ./db/mysql/slave/data:/var/lib/mysql --user 1000
#      - ./db/mysql/slave/config:/etc/mysql/conf.d
#      - ./db/mysql/slave/init:/docker-entrypoint-initdb.d
